import type { ColorType } from '@/theme';
import { BorderRadius } from '@/theme/borderRadius';
import { FontSize } from '@/theme/fonts';

export default (colors: ColorType) => ({
  typography: {
    default: FontSize.MEDIUM,
    smaller: FontSize.SMALL,
    subtext: FontSize.EXTRA_SMALL,
  },
  roundness: {
    default: BorderRadius.SMALL,
    rounded: BorderRadius.FULL,
  },
  colors: {
    primary: {
      border: colors.primary,
      borderHighlight: colors.palette.primary[50],
      borderDisabled: colors.palette.primary[60],
      background: colors.primary,
      backgroundHighlight: colors.palette.primary[50],
      backgroundDisabled: colors.palette.primary[60],
      label: colors.white,
      labelHighlight: colors.white,
      labelDisabled: colors.white,
    },
    secondary: {
      border: colors.secondary,
      borderHighlight: colors.palette.secondary[30],
      borderDisabled: colors.palette.secondary[60],
      background: colors.palette.secondary[60],
      backgroundHighlight: colors.secondary[80],
      backgroundDisabled: colors.palette.secondary[60],
      label: colors.black,
      labelHighlight: colors.black,
      labelDisabled: colors.black,
    },
    custom: {
      border: colors.primary,
      borderHighlight: colors.palette.primary[50],
      borderDisabled: colors.palette.primary[60],
      background: colors.primary,
      backgroundHighlight: colors.palette.primary[50],
      backgroundDisabled: colors.palette.primary[60],
      label: colors.white,
      labelHighlight: colors.white,
      labelDisabled: colors.white,
    },
    black: {
      border: colors.pureBlack,
      borderHighlight: colors.black,
      borderDisabled: colors.pureBlack,
      background: colors.pureBlack,
      backgroundHighlight: colors.black,
      backgroundDisabled: colors.pureBlack,
      label: colors.pureWhite,
      labelHighlight: colors.pureWhite,
      labelDisabled: colors.pureWhite,
    },
    white: {
      border: colors.pureWhite,
      borderHighlight: colors.white,
      borderDisabled: colors.pureWhite,
      background: colors.pureWhite,
      backgroundHighlight: colors.white,
      backgroundDisabled: colors.pureWhite,
      label: colors.pureBlack,
      labelHighlight: colors.pureBlack,
      labelDisabled: colors.pureBlack,
    },
  },
  animationConfig: { duration: 200 },
  minElevationLevel: 0,
  maxElevationLevel: 4,
});
